### ISSUE TITLE
Pages not working

### ISSUE THREAD

**Issue by Dontorpedo** [outer-web/settings#1]
After doing all the steps and creating different pages, always only the last one ist opened, also "Settings" label is not changed when i enter a custom Name or try to use the label method.

**Comment by webmaster254** [comment]
I got the same error
Typed static property Filament\Pages\BasePage::$view must not be accessed before initialization

**Comment by SimonBroekaert** [comment]
Hi @Dontorpedo ,

Your issue is probably with [the filament package](https://github.com/outer-web/filament-settings) that uses this package? I will check this out and solve it for you.

Thank you for using the package and reporting this issue

**Comment by SimonBroekaert** [comment]
Hi @Dontorpedo

I have updated the [README.md](https://github.com/outer-web/filament-settings?tab=readme-ov-file#changing-the-navigation-label) to make it more clear on how to setup multiple pages. 

The problem you are probably facing is that Filament will override pages with the same navigation label.

By default, all pages that extend this package's setting page will have the same label. You can override it by adding the `public static function getNavigationLabel() : string` method to your settings page and returning the wanted label.

You can also override the page title if wanted by overriding the `public function getTitle() : string` method. This is now documented in the README.

Hope this solves your issue! If not, you can always re-open this issue!
